name: Monitor de Eventos
on:
  schedule:
    # Ejecuta cada 10 minutos - formato cron: "minuto hora dia mes dia_semana"
    - cron: '*/10 * * * *'
  # Permite ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Descargar el código
    - name: Checkout código
      uses: actions/checkout@v3
    
    # Paso 2: Configurar Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Paso 3: Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Paso 4: Ejecutar el scraper
    - name: Ejecutar scraper
      run: python scraper.py
      
    # Paso 5: (Opcional) Guardar logs
    - name: Subir logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: /*.log
