name: Monitor de Eventos
on:
  schedule:
    # Ejecuta cada 10 minutos - formato cron: "minuto hora dia mes dia_semana"
    - cron: '*/5 * * * *'
  # Permite ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar código
      uses: actions/checkout@v4  # Versión actualizada
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        pip install requests beautifulsoup4 lxml
        
    - name: Ejecutar scraper
      run: python scraper.py

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_FELIPE: ${{ secrets.TELEGRAM_CHAT_FELIPE }}
  TELEGRAM_CHAT_BELEN: ${{ secrets.TELEGRAM_CHAT_BELEN }}
