name: Monitor de Eventos
on:
  schedule:
    # Ejecuta cada 10 minutos - formato cron: "minuto hora dia mes dia_semana"
    - cron: '*/10 * * * *'
  # Permite ejecución manual desde GitHub
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar código
      uses: actions/checkout@v4  # Versión actualizada
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        pip install requests beautifulsoup4 lxml
        
    - name: Ejecutar scraper
      run: python scraper.py

    - name: Guardar cambios en JSON (si hay nuevos eventos)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add eventos.json
        git diff --staged --quiet || git commit -m "Actualizar eventos notificados"
        git push

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_FELIPE: ${{ secrets.TELEGRAM_CHAT_FELIPE }}
  TELEGRAM_CHAT_BELEN: ${{ secrets.TELEGRAM_CHAT_BELEN }}
